export const allScreenshots = [
  { title: 'Interception Replay', src: '/images/screenshots/replay2.png', alt: 'DashClaw Interception Replay' },
  { title: 'Mission Control', src: '/images/screenshots/Mission Control.png', alt: 'DashClaw Mission Control' },
  { title: 'Decisions', src: '/images/screenshots/Decisions.png', alt: 'DashClaw Decisions Ledger' },
  { title: 'Policies', src: '/images/screenshots/Policies.png', alt: 'DashClaw Policy Engine' },
  { title: 'Approvals', src: '/images/screenshots/Approvals.png', alt: 'DashClaw Approval Queue' },
  { title: 'Agents', src: '/images/screenshots/Agents.png', alt: 'DashClaw Agent Fleet' },
  { title: 'Signals', src: '/images/screenshots/Signals.png', alt: 'DashClaw Integrity Signals' },
  { title: 'Activity', src: '/images/screenshots/Activity.png', alt: 'DashClaw Activity Timeline' },
  { title: 'Compliance', src: '/images/screenshots/Compliance.png', alt: 'DashClaw Compliance Mapping' },
  { title: 'Audit Log', src: '/images/screenshots/Audit Log.png', alt: 'DashClaw System Audit Log' },
  { title: 'Swarm Intel', src: '/images/screenshots/Swarm Intel.png', alt: 'DashClaw Swarm Intelligence' },
  { title: 'Assumptions', src: '/images/screenshots/Assumptions.png', alt: 'DashClaw Assumption Tracking' },
  { title: 'Learning', src: '/images/screenshots/Learning.png', alt: 'DashClaw Learning Analytics' },
  { title: 'Prompts', src: '/images/screenshots/Prompts.png', alt: 'DashClaw Prompt Governance' },
  { title: 'Evaluations', src: '/images/screenshots/Evaluations.png', alt: 'DashClaw Automated Evaluations' },
  { title: 'Quality Scoring', src: '/images/screenshots/Quality Scoring.png', alt: 'DashClaw Quality Scoring' },
  { title: 'Integrations', src: '/images/screenshots/Integrations.png', alt: 'DashClaw Integrations' },
  { title: 'Webhooks', src: '/images/screenshots/Webhooks.png', alt: 'DashClaw Webhooks' },
  { title: 'API Keys', src: '/images/screenshots/API Keys.png', alt: 'DashClaw API Key Management' },
  { title: 'Usage', src: '/images/screenshots/Usage.png', alt: 'DashClaw Resource Usage' },
  { title: 'Settings', src: '/images/screenshots/Settings.png', alt: 'DashClaw Workspace Settings' },
];
